[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloud-ml-enhancement"
version = "0.1.0"
description = "Cloud-ready ML enhancement of Ethiopian-Text-Data-Cleaner"
requires-python = ">=3.11"
dependencies = []
